"""
const tp comes from network.py

"""

import network
import sys
import numpy as np
import itertools
from scipy import optimize


def optimize_size(original_table, tp=network.tp) -> int:
    """
    return the size of smaller pieces based on the computation function and tp
    :param tp: the throughput from network
    :param original_table:
    :return: a tuple represents the shape
    """
    time_woOpt = sys.getsizeof(original_table) / tp + comp_time(original_table.shape)

    def improvement(length):
        package_size = length

        return
    result = optimize.minimize_scalar(improvement())
    if result.success:  # check if solver was successful
        length = int(result.x)
    else :
        length = np.size(original_table)

    return length


def total_time(original_table, piece_shape: tuple) -> float:
    """
    :param original_table:
    :param piece_shape:
    :return: the total time calculated based on the shape of pieces
    """
    n_pieces = np.size(original_table) / np.product(piece_shape)
    trans = size_shape(piece_shape) / network.tp
    comp = comp_time(piece_shape)

    if trans >= comp:
        # transmition takes more time
        return n_pieces * trans + comp
    else:
        return n_pieces * comp + trans


def comp_time(table_shape: tuple) -> float:
    clock_rate = 3 * 10 ** 9  # unit in Hz
    return np.product(table_shape) / clock_rate  # return unit in seconds


def slice_1d(original_table: np.array, length: int) -> list:
    """
    the method will slice the original table into smaller pieces for faster communication

    :param length: the length for sliced list
    :param original_table: np.ndarray
    :return: list of dict of length length, len(list[0])=length
            each element will have (index of first element), list of continuous
    """

    elements = {i: u for i, u in np.ndenumerate(original_table)}
    index = list(elements.keys())
    n_chuncks = int(len(index) / length)

    chunck_index = [index[x * length: (x + 1) * length] for x in range(n_chuncks)]
    if n_chuncks*length != len(elements):
        chunck_index.append(index[n_chuncks * length:])

    sliced_msgs = [{index: elements[index] for index in chunck} for chunck in chunck_index]

    sliced_msgs = [[list(sliced_msg.keys())[0],list(sliced_msg.values())] for sliced_msg in sliced_msgs]

    return sliced_msgs


def unfold_msg(sliced_msg: list, index_list: list) -> dict:
    """
    Unfold the sliced msg to be a dictionary where each entry is (index) : value
    :param sliced_msg: an element in the output list from the slice_1d()
    :param index_list: a list of index, result generated by generate_index()
    :return: a dict {(index) : value}
    """
    position = index_list.index(sliced_msg[0]) # the index of the first element of the sliced_msg
    sub_index_list = index_list[position: len(sliced_msg[1])]
    return dict(zip(sub_index_list, sliced_msg[1] ))


def generate_index(shape: tuple) -> list:
    """
    Given a shape, return the list of index of each element.
    :param shape: (5,4,3)
    :return: a list. such as [(0, 0, 0), (0, 0, 1), (0, 0, 2)...]
    """
    index = [i for i, d in np.ndenumerate(np.zeros(shape))]
    return index


def size_shape(table_dim) -> int:
    """
    gives the size in byte by the table dim, size of dim = tuple(a,b,c)
    :param table_dim: a tuple describe the shape of a table
    :return: size in byte
    """
    return 80 + 16 * len(table_dim) + 8 * np.product(table_dim)


def size_shape_split(table_dim) -> int:
    """
    gives the size in byte by the table dim, size of dim = tuple(a,b,c)
    :param table_dim: a tuple describe the shape of a table
    :return: size in byte
    """
    example = {x:np.random.randint(100) for x in itertools.product(*(range(i) for i in table_dim))}

    return sys.getsizeof(example)


if __name__ == '__main__':
    table = np.random.randint(10, size=(5, 4, 3))
    result = slice_1d(table, 11)
    print(result[0])
    print(unfold_msg(result[0], generate_index(table.shape)))